# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!
  DEMO_BASELINE_TAG: demo-start-2022

tasks:
  create:
    desc: Create the cluster and deploy the applications
    cmds:
      - task: create-cluster
      - task: deploy-applications
    silent: true
  create-cluster:
    desc: Create the cluster using Talos
    cmds:
      - talosctl cluster create -f infrastructure/cluster-template.yaml --talosconfig talosconfig
  deploy-applications:
    desc: Deploy the applications using ArgoCD
    cmds:
      - kubectl apply -f argocd/root-application.yaml
  reset-demo:
    desc: Check out the demo baseline tag in detached HEAD
    cmds:
      - git fetch --tags
      - git switch --detach {{.DEMO_BASELINE_TAG}}
