apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mssql-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/matjahs/mssql-upgrade-demo.git
    targetRevision: HEAD
    path: workloads/mssql
  destination:
    server: https://kubernetes.default.svc
    namespace: sql-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
