kind: Cluster
kubernetes:
  version: v1.35.3
name: demo
features:
  enableWorkloadProxy: true
patches:
  - name: bootstrap-argocd
    inline:
      cluster:
        extraManifests:
          - https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.6/manifests/install.yaml
          - https://raw.githubusercontent.com/matjahs/mssql-upgrade-demo/main/bootstrap/argocd-default-namespace-fixes.yaml
          - https://raw.githubusercontent.com/matjahs/mssql-upgrade-demo/main/bootstrap/argocd-service-exposure.yaml
          - https://raw.githubusercontent.com/matjahs/mssql-upgrade-demo/main/bootstrap/argocd-bootstrap-job.yaml
talos:
  version: v1.12.6
---
kind: ControlPlane
machineClass:
  name: vsphere-small
  size: 3
patches:
- inline:
    cluster:
      allowSchedulingOnControlPlanes: true
  name: cp-schedulable
---
kind: Workers
name: worker
machineClass:
  name: vsphere-small
  size: 2
patches:
  - file: infrastructure/patches/local-path-provisioner-volume.yaml
